// <auto-generated />
namespace Bootcamp20.Micro.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingModelSupplier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingModelSupplier));
        
        string IMigrationMetadata.Id
        {
            get { return "201811140929469_addingModelSupplier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
